server.address=0.0.0.0
server.port=${PORT:8080}

jwt.secret=Em/ik/7gNU3sdo+OL0wNhqotreV3g6s1xYv72ol/pe/makas5jKTdYw3n1985sP2s7L6pQvL0f3S+b8a9v2x1c1m4n5k77
jwt.expiration=86400000

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/urlShortener}

cors.allowed.origins=${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,https://url-shortener-frontend-sepia.vercel.app}